### PR TITLE
Add test for auto-linking in lock descriptions and handling for nil lock authors

### PR DESCRIPTION
**Pull request by girasquid**
@byroot @gmalette 

I forgot to add a test for the auto-linking, so I added that - while I was adding it I also discovered that when `lock_author` is `nil` you'd get a 500 error, so I fixed that too.

### CODE REVIEW

**Comment by gmalette** [comment]
:joy:

**Comment by byroot** [comment]
Hum, is there a legitimate case for the lock author being nil? Because otherwise I'd prefer to avoid such defensive code.

**Comment by girasquid** [comment]
Not sure - the existing tests that use `lock_reason` aren't setting a lock author. I'm not sure if the original implementation was based on lock authors sometimes not having names, or lock authors sometimes being nil. @vernalkick do you remember?

**Comment by byroot** [comment]
Hum, look like Locks created by the API have no author: https://github.com/Shopify/shipit-engine/blob/1ff2b43f190ef120bb74afca5033e6428cb60686/app/controllers/api/locks_controller.rb

I wonder if we could make them created by `Anonymous`.

**Comment by girasquid** [comment]
Future PR?

**Comment by byroot** [comment]
Yeah :shipit: I guess. I'll clean it up afterwards.

**Pull request merged**
