### PR TITLE
Fix GitHubApp for Enterprise installations

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/Shopify/shipit-engine/pull/793

@tebriel I believe this should fix your issue. Unfortunately I don't have any GHE install to test it myself :/

To test this branch you can modify your `Gemfile` as is: 

```ruby 
gem 'shipit-engine', github: 'Shopify/shipit-engine', branch: 'gh-enterprise'
```

and then run `bundle update shipit-engine`.

Please let me know if it works for you.

### CODE REVIEW

**Comment by tebriel** [comment]
I *think* that's working, can you let me know if this error is related? I haven't done much digging into it yet:
```
sidekiq_1     | 2018-05-22T16:25:30.397Z 1 TID-gswyeebg1 Shipit::CacheDeploySpecJob JID-3b1c1503db7ed9b52910b7f2 INFO: fail: 301.797 sec
sidekiq_1     | 2018-05-22T16:25:30.397Z 1 TID-gswyeebg1 WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"Shipit::CacheDeploySpecJob","queue":"default","args":[{"job_class":"Shipit::CacheDeploySpecJob","job_id":"1f9273e8-5d9b-4008-a292-1fb4323e3036","provider_job_id":null,"queue_name":"default","priority":null,"arguments":[{"_aj_globalid":"gid://shipit/Shipit::Stack/1"}],"executions":0,"locale":"en"}],"retry":true,"jid":"3b1c1503db7ed9b52910b7f2","created_at":1527001886.4930522,"enqueued_at":1527003087.120086,"error_message":"Shipit::Command::TimedOut","error_class":"Shipit::Command::TimedOut","failed_at":1527002193.1357877,"retry_count":1,"retried_at":1527003049.9223473},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"Shipit::CacheDeploySpecJob\",\"queue\":\"default\",\"args\":[{\"job_class\":\"Shipit::CacheDeploySpecJob\",\"job_id\":\"1f9273e8-5d9b-4008-a292-1fb4323e3036\",\"provider_job_id\":null,\"queue_name\":\"default\",\"priority\":null,\"arguments\":[{\"_aj_globalid\":\"gid://shipit/Shipit::Stack/1\"}],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"3b1c1503db7ed9b52910b7f2\",\"created_at\":1527001886.4930522,\"enqueued_at\":1527003087.120086,\"error_message\":\"Shipit::Command::TimedOut\",\"error_class\":\"Shipit::Command::TimedOut\",\"failed_at\":1527002193.1357877,\"retry_count\":1,\"retried_at\":1527003049.9223473}"}
sidekiq_1     | 2018-05-22T16:25:30.397Z 1 TID-gswyeebg1 WARN: Shipit::Command::TimedOut: Shipit::Command::TimedOut
sidekiq_1     | 2018-05-22T16:25:30.397Z 1 TID-gswyeebg1 WARN: /usr/local/bundle/bundler/gems/shipit-engine-aac57b56db12/lib/shipit/command.rb:157:in `rescue in block in read_stream'
```

**Comment by casperisfine** [comment]
> can you let me know if this error is related?

It's not. What failed here is `CacheDeploySpecJob` which tries to clone the repository, and according to the logs wasn't able to do it in 5 minutes.

So either the repository is HUGE, or another common issue is that GItHub's keys are not in `~/.ssh/known_hosts` so SSH was prompting to accept the keys.

**Comment by tebriel** [comment]
Okay, then yes this works. Do I need to generate ssh keys for shipit to be able to `git clone` and add them to github? I assumed that it would use the https api since it has the ability to generate credentials. I'm working on a document that helps onboard new deployments with the things I've found. I'll go ahead and make a work-in-progress PR and we can discuss things there.

**Comment by byroot** [comment]
> Do I need to generate ssh keys for shipit to be able to git clone and add them to github?

Yes. Shipit simply assume `git clone git@....` will work, it's up to you to make sure it works. In our case we use ssh-agent so that the key can't be leaked.

> I assumed that it would use the https api since it has the ability to generate credentials. 

You mean clone using `https://` ? It could be interesting to make the setup simpler. I would need to look at that.

**Comment by tebriel** [comment]
Okay, I'll get on that. What user do the ssh keys live under? Do you just have a utility account that has those keys?

**Comment by byroot** [comment]
Oh right. 

> Do you have a shipit user that has the ssh keys registered to them?

Yes. And it is added as read only contributor org.

**Comment by tebriel** [comment]
Thanks again for doing this, as a note, I don't think you did a new release to 0.22.2. I don't know if you intended to, thanks!

**Comment by byroot** [comment]
> I don't think you did a new release to 0.22.2. I don't know if you intended to, thanks!

I was waiting to see if you'd spot other GHE issues (and looks like you did https://github.com/Shopify/shipit-engine/issues/796).

I'm a bit ashamed of how much issues you are finding with GHE, I wish I had a GHE install somewhere so I could tst it myself when I make changes :/

I'll fix your other issue tomorrow and release a new version.

**Comment by tebriel** [comment]
That makes perfect sense. There's no need to be ashamed, it's very hard to write code when you don't even have something to test against. GH and GHE are different beasts, so it's hard to catch all the edge cases for both. I really appreciate your fast responses. I've got one of my side projects at work deploying with shipit (manually clicking the button after merge). Still so much to learn!
Thanks for all the help.

**Pull request merged**
