### PR TITLE
Remove fixed height for header

### PR DESCRIPTION
**Pull request by AnotherJoSmith**
This fixes the header issues with Shipit. This changes works for mobile as well.

Before:

screen shot 2016-11-29 at 2 55 21 pm

After: 

screen shot 2016-11-29 at 2 55 11 pm

@jules2689 for review

### CODE REVIEW

**Comment by RichardBlair** [comment]
:shipit:

**Comment by jules2689** [comment]
While you're in here, mind adding `<meta name="viewport" content="width=device-width, initial-scale=1">` to the `<head>` section in `application.html.erb`? Better responsiveness to go along with the header.

Thanks for this :+1:

**Comment by AnotherJoSmith** [comment]
@jules2689 Added it.

**Comment by sirupsen** [comment]
❤️

**Pull request merged**
