### PR TITLE
Remove "merged" from commit details view

### PR DESCRIPTION
**Pull request by girasquid**
@byroot @pushrax 

Pretty sure this is the only change you need for this, right?

Fixes https://github.com/Shopify/shipit-engine/issues/425.

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Thanks @girasquid :smiley:

**Comment by byroot** [comment]
It won't be consistent with deploy / rollbacks anymore, but yeah ok let's try that.

**Comment by girasquid** [comment]
What do I need to change for those?

**Comment by byroot** [comment]
You shouldn't change those. Otherwise there would be no way to make a distinction between a deploy and a rollback.

**Comment by pushrax** [comment]
:+1:

**Pull request merged**
