### PR TITLE
[ci skip] Add 'Auth callback URL` note to README

### LINKED ISSUE #594: Docs: Setting up Application in Github
I'm having issues setting up my application, specifically the callback URL in GitHub. Is there a specific URL that I should set it to? I'll be happy to send a PR with basic instructions on GitHub App setup for people who haven't set one up before.

### Github Settings
**Homepage URL**: [http://ak-shipit.herokuapp.com/](http://ak-shipit.herokuapp.com/)
**Authorization callback URL**: [http://ak-shipit.herokuapp.com/](http://ak-shipit.herokuapp.com/)
**Hosting**: Heroku
**Error happened after**: `Started GET "/github/auth/github/callback?code=42df00e4df49d6c52b43&origin=http%3A%2F%2Fak-shipit.herokuapp.com%2F&state=6813555bb5fcfcf6dec88daed05b7a3b013dfade53e46c2d"`

### PR DESCRIPTION
**Pull request by alexcameron89**
Closes  #594

### CODE REVIEW

**Comment by byroot** [comment]
Thanks appreciate. Could you also update the in app message there: https://github.com/Shopify/shipit-engine/blob/3e40fc58374925f752d1e124487c4be6bc21daed/app/helpers/shipit/shipit_helper.rb#L34-L39

**Comment by alexcameron89** [comment]
Got it :+1:

**Comment by byroot** [comment]
Thank you!

**Comment by alexcameron89** [comment]
Thanks for the help! I'm excited about this project, it's going to be very helpful.

**Pull request merged**
