### PR TITLE
Bump pubsubstub version

### PR DESCRIPTION
**Pull request by maclover7**
To take advantage of EventMachine removal!

### CODE REVIEW

**Comment by maclover7** [comment]
cc @byroot @gmalette for review

**Comment by byroot** [comment]
Right, it's been a while we're running the event machine free version, and so far no problem have been uncovered. 

@gmalette could you release a `0.1.0`? I'm not a huge fine of having a prerelease gem as dependency.

**Comment by gmalette** [comment]
`0.1.0` released!

**Comment by maclover7** [comment]
@byroot @gmalette updated!

**Comment by casperisfine** [comment]
Thank you!

**Pull request merged**
