### PR TITLE
Fix baseline migration to be compatible with older MySQL

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/Shopify/shipit-engine/issues/597

@pollosp @josacar mind trying this out?

### CODE REVIEW

**Comment by josacar** [comment]
I'll do

**Comment by pollosp** [comment]
👍

**Comment by casperisfine** [comment]
It fixed your issue? Awesome.

**Comment by pollosp** [comment]
ups sorry, miss understanding , I want to say we will try it , I haven't try it yet.

**Comment by casperisfine** [comment]
Haha, no problem. We can always revert if it doesn't :)

**Pull request merged**
