### PR TITLE
Prefer locked stacks in MergeStatusController

### PR DESCRIPTION
**Pull request by DazWorrall**
Ref: https://github.com/Shopify/shipit/issues/934

If multiple stacks match the branch it makes more sense to prefer any locked stacks even if they doesn't use the merge queue, to give the user context that merging may not be desirable.

### CODE REVIEW

**Comment by casperisfine** [comment]
Not sure I'm a fan of that. If someone creates a personal test stack  for an important repo, it will be displayed.

**Comment by DazWorrall** [comment]
> Not sure I'm a fan of that. If someone creates a personal test stack for an important repo, it will be displayed.

If they also lock it, yes. It's already true if people create a test stack and enable the merge queue, though that's admittedly less likely.

The behaviour here is already poorly defined, I'm not convinced this makes things worse - as David experienced, if there is a locked stack and merging is undesirable, that's quite important context. If someone creates a test stack there's no reason to lock it (so long as CD is disabled).

**Comment by casperisfine** [comment]
>  If someone creates a test stack there's no reason to lock it 

I did plenty of that when I was developing various notifications etc.

But if you feel like this change is positive, then :shipit:

**Comment by DazWorrall** [comment]
I'll wait for some other opinions, happy to be outvoted here.

**Comment by JackTLi** [comment]
I don’t love this behaviour but it makes sense in the context of the problem we’re solving

**Pull request merged**
