### PR TITLE
Test with Ruby 2.2

### PR DESCRIPTION
**Pull request by rafaelfranca**

### CODE REVIEW

**Comment by byroot** [comment]
Thanks, I'll merge on :green_heart:

**Comment by byroot** [comment]
Not to :trollface: but the CircleCI build finished 8 minutes ago and the Travis one didn't started yet :p

**Comment by rafaelfranca** [comment]
lol. That is what I was looking. Very strange.

**Comment by rafaelfranca** [comment]
Turbograph seems to be the reason to have not started the build yet

**Comment by byroot** [comment]
Yeah I wonder if the core issue is not that Travis limit the number of concurrent builds for an organization and that liquid / turbograft / active_merchant just keep eating all the allocated capacity.

**Comment by rafaelfranca** [comment]
Yes, it has organization limit. One thing that we can do to improve the situation is distribute the limit across the projects equally.

**Comment by byroot** [comment]
How does that work?

**Comment by rafaelfranca** [comment]
On the concurrent jobs option of this screen

screen shot 2015-05-27 at 11 13 57 pm

**Pull request merged**
