### PR TITLE
Improve the faraday cache middleware

### PR DESCRIPTION
**Pull request by casperisfine**
Fix: https://github.com/Shopify/shipit-engine/issues/935

Since it's quite brittle, I explained the decision in the code comments.

Ultimately I think GitHub is right to add `Vary: Authorization` since different tokens might mean different users with potentially different accesses. However in our case we know that we're always using the same user (actually app) so we can safely disregard that directive.

The only place where we switch users is for [commit deployments](https://github.com/Shopify/shipit-engine/blob/7bcaceaefdd83c4245db02109654cdc81c10fa84/app/models/shipit/commit_deployment.rb#L24), but first it's a `POST` request to it shouldn't be cached, and second if it fails it will be with a permission error which wouldn't be cached either. So really we're fine, the only worry I have is for a potential future feature, and we might be caught off guard by this, but Shipit is relatively stable this days so the risk is low enough IMO.

On another note, it could be interesting to report this to `faraday-http-cache`, it's not exactly a bug, but I expect that other HTTP cache implementations have a way to deal with such cases, and there's no reason faraday-http-cache couldn't do it.

@josacar would you mind deploying this branch on your installation just to make sure I haven't overlooked anything? If it works for you I'll merge and cut a new release ASAP.

### CODE REVIEW

**Comment by josacar** [comment]
@byroot I'll try this now, thanks a lot!

**Comment by josacar** [comment]
No duplicated cache entries so far.

**Comment by josacar** [comment]
Still working great, thanks for your help!

**Comment by byroot** [comment]
👌 I'll cut a release in a bit.

**Comment by casperisfine** [comment]
@josacar I released it as part of `0.28.1`.

**Comment by josacar** [comment]
thanks for your help. You are such a great maintainer!

**Pull request merged**
