### PR TITLE
Change README to tell that it support more databases

### PR DESCRIPTION
**Pull request by rafaelfranca**
PostgreSQL and SQLite3 are supported now

### CODE REVIEW

**Comment by gmalette** [comment]
:+1:

**Comment by byroot** [comment]
:+1: 

While you're at it, we could say: `Ruby 2.1 or superior`. No?

**Comment by rafaelfranca** [comment]
:+1:. I'll update.

**Comment by rafaelfranca** [comment]
I was going to update the .travis.yml but you merged first :smile:

**Comment by byroot** [comment]
Oops sorry. Would you want commit access? That way you could merge yourself.

**Comment by rafaelfranca** [comment]
> Would you want commit access? That way you could merge yourself.

:+1: Thank you :smile:

**Comment by byroot** [comment]
Done! Welcome aboard!

**Comment by rafaelfranca** [comment]
:train: :train:

**Pull request merged**
