### PR TITLE
Optionally record Review Stack latest deployed ref

### PR DESCRIPTION
**Pull request by indiebrain**
If enabled, `update_latest_deployed_ref` creates a branch for each
Review Stack that shipit-engine deploys. In a Repository with high
Review Stack turnover this quickly adds up to a lot of "noise" branches
in the git object database- our flagship monorepo currently has over 3k
such branches. However, in some scenarios it is still useful to record
the "latest deployed ref" of "plain old, manually managed" stacks - in
our case we DO still want to track the latest deployed ref of our
staging and production "environments" of this flagship monorepo.

This allows the host application to en/disable the recording of the
latest deployed ref for Review Stacks independently of "plain old,
manually defined" stacks.

### CODE REVIEW

**Comment by benlangfeld** [comment]
We should probably also prune those branches when a stack is archived.

**Comment by casperisfine** [comment]
Hum, I don't think this feature make sense for review stack. I think I'd just disable it entirely for these without a config.

**Comment by indiebrain** [comment]
@casperisfine , I can get behind that. Addressed by https://github.com/Shopify/shipit-engine/pull/1180/commits/c793e3a26b16bc3ca1ac048bd3ae7c8287ab9050

**Review by casperisfine — APPROVED** [review]
One style nitpick. Also please squash your commits and I'll merge.

**Comment by indiebrain** [comment]
@casperisfine , thanks for your time and the conversation, friend!

**Pull request merged**
