### PR TITLE
Proper GitHub Enterprise support

### PR DESCRIPTION
**Pull request by byroot**
Fixes: https://github.com/Shopify/shipit-engine/issues/430

@gmalette mind :tophat:ing?

### CODE REVIEW

**Comment by byroot** [comment]
Note to self: update README.

**Comment by byroot** [comment]
Works fine on my end. @mathieugagne would you mind giving this branch a shot?

You'll have to add `github_domain` in your `secret.yml`:

Example:
```yml
development:
  github_domain: github.example.com
```

**Comment by mathieugagne** [comment]
:ok_hand: All good on my end

**Comment by byroot** [comment]
Awesome thanks!

**Comment by gmalette** [comment]
Can you add tests please

**Comment by byroot** [comment]
Right the `Shipit` module should be tested.

**Comment by byroot** [comment]
https://github.com/Shopify/shipit-engine/commit/313d0044b7ccb29411c9f6b18c1c4e77822d7f20

**Pull request merged**
