### PR TITLE
Set html lang attribute in layout

### PR DESCRIPTION
**Pull request by casperisfine**
Hopefully that should fix:

image

@disaacs for review please.

### CODE REVIEW

**Comment by disaacs** [comment]
👍  Worth a shot. No harm in trying.

However I am skeptical. Only the ShipIt home pages shows the translate prompt, none of the specific stack pages do, even though they also have no lang attribute.

**Comment by casperisfine** [comment]
Yes, but chrome's lang detector only triggers if the language declared is different from your system language, or is not declared at all.

On other pages, there is probably nothing that makes chrome think it's not english, whereas some stack name must look like Danish for Chrome.

**Comment by Edouard-chin** [comment]
Worth trying, but I'm skeptical too. We should maybe just disable the chrome feature
```
<meta name="google" content="notranslate" />
```

**Comment by casperisfine** [comment]
@Edouard-chin oops, I merged just before you answered.

I'd prefer for avoid browser specific tags if possible, but if it doesn't work I'll do that. Thanks for the input.

**Comment by disaacs** [comment]
Just tested it in production. It works. I am no longer getting the translate prompt.

**Pull request merged**
